mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    login_view,
    set_cookie_view,
    get_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegistrationView,
    FooBarView,
    HelloView,
)

app_name = 'myauth'

# LoginView избавляет от необходимости писать функцию аутентификации, так как в классе уже реализована логика
# При этом, в шаблоне достаточно указать форму form.as_p и не расписывать поля
# В settings проекта в самом конце необходимо указать адрес перенаправления по умолчанию (LOGIN_REDIRECT_URL)
# Если уже выполнен вход и чтобы не заходить на страницу login, прописываем redirect_authenticated_user=True
urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='myauth/login_form.html',
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    # path('login/', login_view, name='login'),
    # path('logout/', logout_view, name='logout'),
    path('cookie/set/', set_cookie_view, name='set_cookie'),
    path('cookie/get/', get_cookie_view, name='get_cookie'),
    path('session/set/', set_session_view, name='set_cookie'),
    path('session/get/', get_session_view, name='get_cookie'),
    path('about_me/', AboutMeView.as_view(), name='about_me'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('foo_bar/', FooBarView.as_view(), name='foo_bar'),
    path('hello/', HelloView.as_view(), name='hello'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from .sitemaps import sitemaps
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


# Чтобы в проекте появилась документация, устанавливаем библиотеку docutils командой pip install docutils.
# Замораживаем зависимости командой pip freeze > requirements.txt. В settings.py в INSTALLED_APPS добавляем
# 'django.contrib.admindocs', а в MIDDLEWARES 'django.contrib.admindocs.middleware.XViewMiddleware'. Затем в urls.py
# указываем путь path('admin/doc/', include('django.contrib.admindocs.urls')), который должен быть выше
# чем path('admin/', admin.site.urls), иначе документация в админке не будет работать.
urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    # path('api_shop/', include('shopapp.urls')),
    path('blog/', include('blogapp.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps,}, name='django.contrib.sitemaps.views',),
]

# подключение приложения для возможности переводить страницу на нужный язык
urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

# если статус сервера DEBUG, то, чтобы он имел доступ к медиа файлам, необходимо сделать пути к static с помощью static
if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )  # данные параметры необходимо объявить в настройках, так как по умолчанию их значение - пустая строка. Не указав
    #  эти значения, все файлы приложения будут доступны через браузер, а этого допустить нельзя.

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__', include('debug_toolbar.urls')),
    )

mysite/shopapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter

from .views import (
    ProductsListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    OrdersListView,
    OrderDetailView,
    ProductViewSet,
    )

app_name = 'shopapp'

routers = DefaultRouter()
routers.register('products', ProductViewSet)

urlpatterns = [
    path('api_products/', include(routers.urls)),
    path('products/', cache_page(60 * 3)(ProductsListView.as_view()), name='products_list'),
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    path('products/export/', ProductsDataExportView.as_view(), name='products_export'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('products/<int:pk>/archive/', ProductDeleteView.as_view(), name='archive_product'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_details'),
]

mysite/shopapp/forms.py
from django import forms
from django.core import validators

from .models import Product
from django import forms


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = 'name', 'price', 'discount', 'description', 'preview'

    images = forms.ImageField(
        widget=forms.ClearableFileInput(),
    )

    # данное поле в форме с widget позволяет загружать сразу несколько картинок разом
    # images = forms.ImageField(
    #     widget=forms.ClearableFileInput(
    #         attrs={'multiple': True},),
    # )

# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(max_digits=8, decimal_places=2, min_value=1)
#     description = forms.CharField(label='Product description',
#                                   validators=[validators.RegexValidator(
#                                       regex=r'great',
#                                       message='field must contain "great"',
#                                   )],
#                                   widget=forms.Textarea(attrs={
#                                       'cols': 50,
#                                       'rows': 6,
#                                   }
#                                   ))
#     discount = forms.IntegerField(min_value=1, max_value=15)


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view для интернет-магазина: по товарам, заказам и т.д.
"""
import logging
from csv import DictWriter

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.cache import cache
from django.http import HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, HttpResponse, redirect, reverse, get_object_or_404
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action
from rest_framework.parsers import MultiPartParser

from .common import save_csv_products
from .models import Product, Order, ProductImage
from .forms import ProductForm
from .serializers import ProductSerializer

from drf_spectacular.utils import extend_schema, OpenApiResponse

# создание логгера для логирования в разных местах конкретного модуля
# в логгинг нужно передавать не отформатированную строку, а правило, по которому будет идти форматирование
log = logging.getLogger(__name__)


# Чтобы документировать функции и классы и не пропуская параметры, то необходимо установить библиотеку
# flake8 командой pip install flake8. А затем установить расширение для этой библиотеки flake8docstrings
# командой pip install flake8-docstrings. А после заморозить зависимости: pip freeze > requirements.txt
# flake8 проверяет файлы на принадлежность стилю PEP8 командой flake8 приложение/файл.py
@extend_schema(description='Product views CRUD')
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product.
    Полный CRUD для сущностей товара.
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    # поля поиска для SearchFilter
    search_fields = [
        'name',
        'descriptions',
    ]
    # поля поиска для DjangoFilterBackend
    filterset_fields = [
        'name',
        'description',
        'price',
        'discount',
        'archived',
    ]
    # поля поиска для OrderingFilter
    ordering_fields = [
        'name',
        'price',
        'discount',
    ]

    # настройка кэширования данных для конкретного метода в django REST
    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        return super().list(*args, **kwargs)
    
    # с переопределением метода retrieve, extend_schema позволяет добавить описание в API приложении
    @extend_schema(
        summary='Get one product by ID',
        description='Retrieves **product**, returns 404 if not found',
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description='Empty response, product by ID not found'),
        },
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    # экспорт файлов из REST API
    @action(methods=['get'], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type='text/csv')  # подготовка объекта, в который будут выводиться данные
        filename = 'products_export.csv'
        # скачивание файла уже с готовым именем
        response['Content-Disposition'] = f'attachment; filename={filename}'
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            'name',
            'description',
            'price',
            'discount',
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
               field: getattr(product, field) for field in fields
            })

        return response

    # загрузка файлов в REST API
    # Так как загрузка файла со страницы невозможна из-за того, что используется только метод post
    # в терминале пишется команда на уровне, где расположен файл для импорта:
    # curl -X POST -F 'название файла с расширением' (адрес на страницу импорта файлов в REST API)
    @action(methods=['post'], detail=False, parser_classes=[MultiPartParser])
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES['file'].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


# вариант реализации списка товаров с помощью ListView (наследника TemplateView)
class ProductsListView(ListView):
    template_name = 'shopapp/products_list.html'
    # model = Product #указывается, если не указывается queryset
    context_object_name = 'products'  # имя, по которому будет доступен список продуктов
    queryset = Product.objects.filter(archived=False)


# вариант реализации списка продуктов с помощью View
# class ProductsListView(View):
#
#     def get(self, request: HttpRequest) -> HttpResponse:
#         products = Product.objects.all()
#         context = {
#             'products': products,
#         }
#
#         return render(request, 'shopapp/products_list.html', context=context)


# вариант реализации списка продуктов с помощью TemplateView (наследник View)
# class ProductsListView(TemplateView):
#
#     template_name = 'shopapp/products_list.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['products'] = Product.objects.all()
#         return context

# вариант реализации списка товаров с помощью DetailView (наследника TemplateView)
class ProductDetailView(DetailView):
    template_name = 'shopapp/product_details.html'
    # model = Product  #указывается, если не указывается queryset
    context_object_name = 'product'
    queryset = Product.objects.prefetch_related('images').filter(archived=False)


# реализация деталей продукта с помощью View
# class ProductDetailView(View):
#
#     def get(self, request: HttpRequest, pk: int) -> HttpResponse:
#         product = get_object_or_404(Product, pk=pk) #при отсутствии продукта будет ошибка 404, а не серверная ошибка
#         context = {
#             'product': product
#         }
#
#         return render(request, 'shopapp/product_details.html', context=context)


# реализация создания продукта с помощью CreateView (наследник ModelForm)
# миксин UserPassesTestMixin делает проверку есть ли разрешение у пользователя на создание продукта
class ProductCreateView(CreateView):
    # def test_func(self):
    #     return self.request.user.is_superuser  #проверка на суперюзера, так как только он может создавать продукт
    model = Product
    fields = 'name', 'price', 'discount', 'description', 'preview'
    success_url = reverse_lazy('shopapp:products_list')
    # есть вариант использовать form_class = 'название формы' вместо fields и тогда
    # не надо будет описывать поля в классе, что должны быть в шаблоне
    # при создании шаблона нужно указать имя МОДЕЛИ и суффикс _FORM


# реализация изменения (обновления) описания продукта с помощью UpdateView (наследник ModelForm)
class ProductUpdateView(UpdateView):
    model = Product
    # fields = 'name', 'price', 'discount', 'description', 'preview'
    form_class = ProductForm  # указывается, если создана форма в файле forms.py
    template_name_suffix = '_update_form'  # коррекция суффикса при создании шаблона

    def get_success_url(self):
        return reverse('shopapp:product_details', kwargs={'pk': self.object.pk})

    # обработка формы
    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist('images'):  # получение картинок из поля 'images' и сохранение в объект
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


# реализация удаления или сокрытия продукта с помощью DeleteView (наследник ModelForm)
class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')
    # при создании шаблона нужно указать имя МОДЕЛИ и суффикс _CONFIRM_DELETE

    # реализация архивирования продукта (soft delete)
    def form_valid(self, form):  # метод для удаления в DeleteView
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


# вариант реализации списка заказов с помощью ListView (наследника TemplateView)
# Миксин LoginRequiredMixin должен быть первым так как проверяет пользователя на право просматривать страницу. Если он
# не аутентифицирован, то доступ запрещен.
class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (Order.objects.select_related('user').prefetch_related('products'))
    # при таком наборе параметров, шаблон должен называться именем МОДЕЛИ и с суффиком _LIST
    # обращение к списку заказов идет через OBJECT_LIST, если не указывать context_object_name


# вариант реализации списка заказов с помощью View
# class OrdersListView(View):
#
#     def get(self, request: HttpRequest) -> HttpResponse:
#         orders = Order.objects.select_related('user').prefetch_related('products')
#         context = {
#             'orders': orders
#         }
#         return render(request, 'shopapp/order_list.html', context=context)


# вариант реализации деталей заказа с помощью DetailView (наследника TemplateView)

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Base body
    {% endblock %}
    <div>
        <p>
            Time now: {% now 'H:i' %}
        </p>
    </div>
</body>
</html>

mysite/shopapp/templates/shopapp/create_product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
<h1>
    Create product
</h1>
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Create
        </button>
    </form>
</div>
<div>
    <p>
        <a href="{% url 'shopapp:products_list' %}">
            Back to products list
        </a>
    </p>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
Order details
{% endblock %}

{% block body %}
<h1>
    Order details
</h1>
<div>
    <p>
        User by: {% firstof object.user.first_name object.user.username %}
    </p>
    <p>
        Delivery address: {{ object.delivery_address }}
    </p>
    <p>
        Promocode: {{ object.promocode }}
    </p>
    <p>
        {% if object.products %}
        <p>
            <ul>
                {% for product in object.products.all %}
                <li>
                    {{ product.name }} for ${{ product.price }}
                </li>
                {% endfor %}
            </ul>
            {% else %}
                <h3>
                    No products yet
                </h3>
            {% endif %}
        </p>
    </p>
</div>
<div>
    <p>
        <a href="{% url 'shopapp:orders_list' %}">
            Back to orders list
        </a>
    </p>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders
{% endblock %}

{% block body %}
  <h1>Orders</h1>
  {% if object_list %}
    {% for order in object_list %}
      <div>
        <p>
          <a href="{% url 'shopapp:order_details' pk=order.pk %}">
            Order #{{ order.pk }}
          </a>
        </p>
      </div>
    {% endfor %}
  {% else %}
    <h3>
      No orders yet
    </h3>
  {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Archived product
{% endblock %}

{% block body %}
    <h1>
        Archived product
    </h1>
    <h2>
        Are you sure want to archived product {{ object.name }}?
    </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Archived
        </button>
    </form>
    <div>
        <p>
            <a href="{% url 'shopapp:product_details' pk=object.pk %}">
                Back to product details
            </a>
        </p>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product details
{% endblock %}

{% block body %}
    <h1>
        Details {{ product.name }}
    </h1>
    <div>
        <p>
            Price: {{ product.price }}
        </p>
        <p>
            Description: {% firstof product.description 'No description' %}
        </p>
        <p>
            Discount: {% firstof product.discount 'No discount' %}
        </p>
        <p>
            Archived: {{ product.archived }}
        </p>
    </div>
    {% if product.preview %}
        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}
    <h3>
        Images:
    </h3>
        <div>
            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="img.image.name">
                    <div>
                        Description: {{ img.description }}
                    </div>
                </div>
            {% empty %}
                <div>
                    No images yets
                </div>
            {% endfor %}
        </div>
    <div>
        <p>
            <a href="{% url 'shopapp:products_list' %}">
                Back to product list
            </a>
        </p>
        <p>
            <a href="{% url 'shopapp:update_product' pk=product.pk %}">
                Update product
            </a>
        </p>
        <p>
            <a href="{% url 'shopapp:archive_product' pk=product.pk %}">
                Archive product
            </a>
        </p>

    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>
        Create a new product
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Create
        </button>
    </form>
    <div>
        <p>
            <a href="{% url 'shopapp:products_list' %}">
                Back to products list
            </a>
        </p>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>
        Update product
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Update
        </button>
    </form>
    <div>
        <p>
            <a href="{% url 'shopapp:product_details' pk=object.pk %}">
                Back to product details
            </a>
        </p>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
<li>
  <a href="{% url 'admin:import_products_csv' %}" class="addLink">
    ImportCSV
  </a>
</li>
{{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/products_list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
{% translate 'Products list' %}
{% endblock%}

{% block body %}
<h1>{% translate 'Products list' %}</h1>
{% if products %}
<div>
{% blocktranslate count products_count=products|length %}
There is only one product.
{% plural %}
There are {{ products_count }} products.
{% endblocktranslate %}
</div>
{% for product in products %}
<div>
    <p>
        <a href="{% url 'shopapp:product_details' pk=product.pk %}">
            {% translate 'Name' context 'product name' %}: {{ product.name }}
        </a>
    </p>
    <p>
        {% translate 'Price' %}: {{ product.price }}
    </p>
    {% if product.preview %}
        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}
</div>
<br>
{% endfor %}
<div>
    <p>
        <a href="{% url 'shopapp:create_product' %}">
            {% translate 'Create a new product' %}
        </a>
    </p>
</div>
{% else %}
{% url 'shopapp:create_product' as create_product_url %}
{% blocktranslate %}
<h3>'No products yet'</h3>
<a href="{{ create_product_url }}">
    'Create a new product'
</a>
{% endblocktranslate %}

{% endif %}

{% endblock%}